apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: muchtodo
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  # ClusterIP means only accessible inside the cluster (default)
  type: ClusterIP