apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
stringData:
  # Base64 encoding happens automatically with stringData
  mongo-root-username: "root"
  mongo-root-password: "example"